server:
  port: 20010
spring:
  profiles:
    include: common
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 172.21.143.236:8848
alipay:
  app-id: 9021000149696261
  private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDOJXeyFsk3o6zyylqxgi3cPI4Qa/WPhplzI+8OxwguwuABnj3IzADDYiYjmf/pulkJI2r3Fbd8SRz1DCylq395VVgb4tWofEXqXbUYrY++nNryt6r+bPWPg+ocbC/0VKMiFS4dL25cH9MVHyOSxC7aShm0ISYS+LzHLL9x9yZbUgwC3Wzmu09Ab3p9cvewmCrG3NPpvBJvFaVJFlXj/aRsQc9KRUb8XTao6Ml/3k92i3ddEks2bP901rqWQM1JrAFsjJbTLU5QILrmn+NOStUmrADaTRO9MJXNsh1+2LzK70tWQiGKLRz33cmHpGqZIDCP1wPODWG45vw0N5TKIXirAgMBAAECggEAECCAP69mqHKmigvoknBztAIMvx4jBMpr4MUT450Qd9AJBDdj7/x9pstb3ncivR817fAWYyQQyalSmZ0NNRy4iT5y+SOCwX6PXaldDIQvdaMBwfE6cFMH1uVkADs6eSvR402y4NegE5btxX49IzMz0yHu5tedCejpo89NXtYN6yDZAYazLvRyb0Ztq6Te/uQ/TdhHzcAFVj1GDVrNbpg7wIILBjTuJ+uoXw9cog5a5aJRIHPhSLKghgQzx87Jxq2ZIfpD8OSQ8LclssNKx1gypj3F8os5I+YrtulxHwDTbpXbpon1RwFsVMQoREz+F3WOL4DDezR6oL20tw9WXTV3IQKBgQD34LkcjsCGT5XgD3v8rVJsLysuC7RbFMyvjt3gBgDJNxhw72anTEFhxMa37x0zMH4W0rkpoiIzuR2CsEO/lt/8rrUcAEzt9OvoSop8+P5NrC6xF5emS2KFWA+E4HzW9YHM1frHhasyV8Vs1QIGnRM41i5HZ/lGekbc0a8AD/EPsQKBgQDU5rAWVxlsbmKeXtu8XD0YtvjRdMhmADpD8GdbYix5TfAex4X6EmI4hOBseGNkE3XyM+p+33GhtWVX2qzvESY0ZcrNGnQIaZUSBwmwTNyVI0mfb5BYEVJAvUeE35KNImhwc1Dl1Anp6rf+AR0z+kVO8/tfrVVGkwsagNbnFl8hGwKBgFSKgJgM1/z3B9bzcQYs1v+u1rtNoqWt4mG+CE5vvbTi5aMfA5PrniEKS/xPwVXEJD0EgcKBWcjqSfZYx8KAYsR7kamLMLG35v3C7pjRE2rKXuJneYFuFJwF/MUFC48FDNAf6vhBzrHM3bjQrXA0AmpQIliYTZyL9784hMcwqLcBAoGAMXFxq36G1Pu9w3HcLh5twfOcTWiFscqTvXtzRXHDSlijT0KfBriGPwH87LP4wSET3y/XYaeayCdMZd7PEqY07S5GruNZ1ypOCGXCBkOTZr9PNcu/BfTf2VEb7uvNKSG4h4UAYJ+hvcVY/ZBcq9mPhwp6cnnauA0mIv2Q6xHy/ckCgYEAiNmWk+HX5ajEv3WUVYD4Ywdx5OerzQy+BPZjyCBcgLYnSpqmIQaVZ3v9bUkg8DhqO/3TIgRgS3iqWAJE0MnTHTh3oGaYi2ivDGN6gZyr5kWAcRku8EPnzWGVX4nf2veVv4at1wlHF10AhQMCtAbq+KK6obEkE2KMlfFJN8ez+gk=
  alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1wOaRKm1T0xXC9YnDu/sh+p4resr9SDhioHBf+846wcOaB1aZXfUUKvXq/JaUeDpUbWDgsWh9ABlgbs6oGJvoydO+uWsPjgJOiOVHJbFdZZVYKnT71uzIxfuQbcFGt1xxU3HyrrAwTkYCeHNOrDsudtxdwZHLliCwDMRlkTpz85+hG8ltTHRa+TPuzepdtt915ZMdKcFQhX7xu0AN+h7tZ9uUJvDe55su2plYdh/aEQdzgQOijfEu0mkfEh4TmEeTxCOCsfoiEQQMpHidiSZc1eHG6Pc413HxgbOeNOfPNXWhv5XIjzNi6QK+w7fl0v+bXk69iSbCUKEGXWOAFNkewIDAQAB
  gateway-url: openapi-sandbox.dl.alipaydev.com
  return-url:  http://localhost:20010/api/front/payment/alipay/return/%s
coin:
  exchange-rate: 100 # 1元 = 100金币
management:
  # 端点启用配置
  endpoint:
    logfile:
      # 启用返回日志文件内容的端点
      enabled: true
      # 外部日志文件路径
      external-file: logs/novel-payment-service.log
