server:
  port: 20005
spring:
  application:
    name: novel-monitor
  cloud:
    nacos:
      discovery:
        server-addr: 172.21.143.236:8848
  boot:
    admin:
      discovery:
        services:
          - novel-home-service
          - novel-news-service
          - novel-resource-service
          - novel-book-service
          - novel-user-service
          - novel-author-service
          - novel-search-service
          - novel-gateway

